# Generated by Django 3.2.25 on 2025-09-02 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=75, unique=True)),
                ('network', models.CharField(choices=[('mainnet', 'Mainnet'), ('chipnet', 'Chipnet')], max_length=15)),
                ('passcode', models.CharField(max_length=10)),
                ('payout_satoshis', models.PositiveIntegerField()),
                ('owner_address', models.CharField(max_length=75)),
                ('claim_count', models.PositiveIntegerField(default=0)),
                ('max_claim_count', models.PositiveIntegerField(blank=True, null=True)),
                ('subscribed', models.BooleanField(default=False, help_text='If subscribed to watchtower')),
            ],
        ),
        migrations.CreateModel(
            name='FaucetClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('mainnet', 'Mainnet'), ('chipnet', 'Chipnet')], max_length=15)),
                ('txid', models.CharField(max_length=64)),
                ('recipient', models.CharField(max_length=75)),
                ('satoshis', models.PositiveIntegerField()),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faucet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='main.faucetcontract')),
            ],
        ),
    ]
