# Generated by Django 3.2.25 on 2025-09-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucetcontract',
            name='max_claim_per_ip',
            field=models.PositiveIntegerField(blank=True, help_text='Max claim per unique IP for 24 hours, leave blank to disable', null=True),
        ),
    ]
